package karel;

public class Karel extends javax.swing.JFrame
{
    /**
     * Creates new form Karel
     */
    public Karel()
    {
        this.setTitle("Karel");
        initComponents();
        manualPanel.setVisible(true);
        buttonPanel.setVisible(false);
        InitUI();
    }
    
    public void InitUI()
    {
        //Board board = new Board();
        //add(board);

        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //setSize(board.getBoardWidth() + OFFSET,
        //        board.getBoardHeight() + 2*OFFSET);
        //setLocationRelativeTo(null);
        //setTitle("Sokoban");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainContainer = new javax.swing.JPanel();
        topSubContainer = new javax.swing.JPanel();
        ButtonMode = new javax.swing.JButton();
        ManualMode = new javax.swing.JButton();
        Run = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        bottomSubContainer = new javax.swing.JPanel();
        middleContainer = new javax.swing.JPanel();
        leftContainer = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        GoButton = new javax.swing.JButton();
        LeftButton = new javax.swing.JButton();
        RightButton = new javax.swing.JButton();
        GetButton = new javax.swing.JButton();
        PutButton = new javax.swing.JButton();
        manualPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        rightContainer = new javax.swing.JPanel();
        world = new karel.World();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        New = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        Close = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1006, 550));
        setPreferredSize(new java.awt.Dimension(990, 546));
        setResizable(false);

        mainContainer.setBackground(new java.awt.Color(51, 0, 0));
        mainContainer.setLayout(new java.awt.BorderLayout());

        topSubContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        topSubContainer.setFocusable(false);
        topSubContainer.setMaximumSize(new java.awt.Dimension(32767, 28));
        topSubContainer.setMinimumSize(new java.awt.Dimension(100, 28));
        topSubContainer.setPreferredSize(new java.awt.Dimension(733, 28));

        ButtonMode.setText("Button Mode");
        ButtonMode.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonModeActionPerformed(evt);
            }
        });

        ManualMode.setText("Manual Mode");
        ManualMode.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ManualModeActionPerformed(evt);
            }
        });

        Run.setText("Run");

        Stop.setText("Stop");

        javax.swing.GroupLayout topSubContainerLayout = new javax.swing.GroupLayout(topSubContainer);
        topSubContainer.setLayout(topSubContainerLayout);
        topSubContainerLayout.setHorizontalGroup(
            topSubContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topSubContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManualMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Run)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Stop)
                .addGap(0, 693, Short.MAX_VALUE))
        );
        topSubContainerLayout.setVerticalGroup(
            topSubContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topSubContainerLayout.createSequentialGroup()
                .addGroup(topSubContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonMode)
                    .addComponent(ManualMode)
                    .addComponent(Run)
                    .addComponent(Stop))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        mainContainer.add(topSubContainer, java.awt.BorderLayout.PAGE_START);

        bottomSubContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        bottomSubContainer.setMaximumSize(new java.awt.Dimension(32767, 30));
        bottomSubContainer.setMinimumSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout bottomSubContainerLayout = new javax.swing.GroupLayout(bottomSubContainer);
        bottomSubContainer.setLayout(bottomSubContainerLayout);
        bottomSubContainerLayout.setHorizontalGroup(
            bottomSubContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        bottomSubContainerLayout.setVerticalGroup(
            bottomSubContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        mainContainer.add(bottomSubContainer, java.awt.BorderLayout.PAGE_END);

        middleContainer.setBackground(new java.awt.Color(153, 153, 153));
        middleContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        middleContainer.setMaximumSize(new java.awt.Dimension(2147483647, 438));
        middleContainer.setPreferredSize(new java.awt.Dimension(975, 436));
        middleContainer.setLayout(new java.awt.BorderLayout());

        leftContainer.setMaximumSize(new java.awt.Dimension(430, 32767));
        leftContainer.setMinimumSize(new java.awt.Dimension(430, 100));
        leftContainer.setPreferredSize(new java.awt.Dimension(395, 436));
        leftContainer.setLayout(new java.awt.CardLayout());

        buttonPanel.setVisible(false);

        GoButton.setText("Go");
        GoButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GoButtonActionPerformed(evt);
            }
        });

        LeftButton.setText("Left");
        LeftButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LeftButtonActionPerformed(evt);
            }
        });

        RightButton.setText("Right");
        RightButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RightButtonActionPerformed(evt);
            }
        });

        GetButton.setText("Get");
        GetButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GetButtonActionPerformed(evt);
            }
        });

        PutButton.setText("Put");
        PutButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(LeftButton)
                        .addGap(71, 71, 71)
                        .addComponent(RightButton))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(GoButton))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(GetButton)
                        .addGap(41, 41, 41)
                        .addComponent(PutButton)))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {GetButton, GoButton, LeftButton, PutButton, RightButton});

        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(GoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LeftButton)
                    .addComponent(RightButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GetButton)
                    .addComponent(PutButton))
                .addContainerGap(321, Short.MAX_VALUE))
        );

        leftContainer.add(buttonPanel, "card2");

        manualPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Some BS here about welcome to karel or map info etc.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        manualPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Manual Programmer text box\n\nChange the name of this textbox so its not \n\n\n\n\nso\n\n\n\n\ngeneric\n\nand\n\ntesting\nthe\nscroll\nbar\ndoes\nit\nwork\nor\ndoes\nit\nsuck");
        jScrollPane1.setViewportView(jTextArea1);

        manualPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        leftContainer.add(manualPanel, "card3");

        middleContainer.add(leftContainer, java.awt.BorderLayout.LINE_START);

        rightContainer.setMinimumSize(new java.awt.Dimension(589, 100));
        rightContainer.setPreferredSize(new java.awt.Dimension(589, 469));
        rightContainer.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout worldLayout = new javax.swing.GroupLayout(world);
        world.setLayout(worldLayout);
        worldLayout.setHorizontalGroup(
            worldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        worldLayout.setVerticalGroup(
            worldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        rightContainer.add(world);

        middleContainer.add(rightContainer, java.awt.BorderLayout.CENTER);

        mainContainer.add(middleContainer, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        New.setText("New");
        jMenu1.add(New);

        Save.setText("Save");
        jMenu1.add(Save);

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CloseActionPerformed(evt);
            }
        });
        jMenu1.add(Close);

        jMenuItem4.setText("jMenuItem4");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonModeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ButtonModeActionPerformed
    {//GEN-HEADEREND:event_ButtonModeActionPerformed
        manualPanel.setVisible(false);
        buttonPanel.setVisible(true);
    }//GEN-LAST:event_ButtonModeActionPerformed

    private void GoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GoButtonActionPerformed
    {//GEN-HEADEREND:event_GoButtonActionPerformed
        world.choiceMade("go");
        world.repaint();
        buttonPanel.setVisible(false);
    }//GEN-LAST:event_GoButtonActionPerformed

    private void LeftButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LeftButtonActionPerformed
    {//GEN-HEADEREND:event_LeftButtonActionPerformed
        world.choiceMade("left");
        world.repaint();
    }//GEN-LAST:event_LeftButtonActionPerformed

    private void RightButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RightButtonActionPerformed
    {//GEN-HEADEREND:event_RightButtonActionPerformed
        world.choiceMade("right");
        world.repaint();
    }//GEN-LAST:event_RightButtonActionPerformed

    private void GetButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GetButtonActionPerformed
    {//GEN-HEADEREND:event_GetButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GetButtonActionPerformed

    private void PutButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PutButtonActionPerformed
    {//GEN-HEADEREND:event_PutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PutButtonActionPerformed

    private void ManualModeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ManualModeActionPerformed
    {//GEN-HEADEREND:event_ManualModeActionPerformed
        manualPanel.setVisible(true);
        buttonPanel.setVisible(false);
    }//GEN-LAST:event_ManualModeActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CloseActionPerformed
    {//GEN-HEADEREND:event_CloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Karel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Karel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Karel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Karel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                // Create a new karel world 
                Karel karel = new Karel();
                karel.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonMode;
    private javax.swing.JMenuItem Close;
    private javax.swing.JButton GetButton;
    private javax.swing.JButton GoButton;
    private javax.swing.JButton LeftButton;
    private javax.swing.JButton ManualMode;
    private javax.swing.JMenuItem New;
    private javax.swing.JButton PutButton;
    private javax.swing.JButton RightButton;
    private javax.swing.JButton Run;
    private javax.swing.JMenuItem Save;
    private javax.swing.JButton Stop;
    private javax.swing.JPanel bottomSubContainer;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel leftContainer;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel manualPanel;
    private javax.swing.JPanel middleContainer;
    private javax.swing.JPanel rightContainer;
    private javax.swing.JPanel topSubContainer;
    private karel.World world;
    // End of variables declaration//GEN-END:variables
}
