/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package karel;
/**
 *
 * @author Sam
 */
public class Karel extends javax.swing.JFrame
{
    private final int OFFSET = 0;
    /**
     * Creates new form Karel
     */
    public Karel()
    {
        this.setTitle("Karel");
        initComponents();
        manualPanel.setVisible(false);
        buttonPanel.setVisible(true);
        InitUI();
        
    }
    
    public void InitUI() 
    {
        //edit
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        mainContainer = new javax.swing.JPanel();
        topSubContainer = new javax.swing.JPanel();
        ButtonMode = new javax.swing.JButton();
        ManualMode = new javax.swing.JButton();
        Run = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        GemLabel = new javax.swing.JLabel();
        gemcounter = new javax.swing.JLabel();
        StepLabel = new javax.swing.JLabel();
        Stepcounter = new javax.swing.JLabel();
        bottomSubContainer = new javax.swing.JPanel();
        middleContainer = new javax.swing.JPanel();
        leftContainer = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        Go = new javax.swing.JButton();
        Left = new javax.swing.JButton();
        Right = new javax.swing.JButton();
        Get = new javax.swing.JButton();
        Put = new javax.swing.JButton();
        manualPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        rightContainer = new javax.swing.JPanel();
        world = new karel.World();
        MenuBar = new javax.swing.JMenuBar();
        SaveCodeChoice = new javax.swing.JMenu();
        New = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        Close = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1006, 550));
        setPreferredSize(new java.awt.Dimension(990, 546));
        setResizable(false);

        mainContainer.setBackground(new java.awt.Color(51, 0, 0));
        mainContainer.setLayout(new java.awt.BorderLayout());

        topSubContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        topSubContainer.setFocusable(false);
        topSubContainer.setMaximumSize(new java.awt.Dimension(32767, 28));
        topSubContainer.setMinimumSize(new java.awt.Dimension(100, 28));
        topSubContainer.setPreferredSize(new java.awt.Dimension(733, 28));

        ButtonMode.setText("Button Mode");
        ButtonMode.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ButtonModeActionPerformed(evt);
            }
        });

        ManualMode.setText("Manual Mode");
        ManualMode.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ManualModeActionPerformed(evt);
            }
        });

        Run.setText("Run");
        Run.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RunActionPerformed(evt);
            }
        });

        Stop.setText("Stop");

        GemLabel.setText("Gems:");

        gemcounter.setText("0");

        StepLabel.setText("Steps:");

        Stepcounter.setText("0");

        javax.swing.GroupLayout topSubContainerLayout = new javax.swing.GroupLayout(topSubContainer);
        topSubContainer.setLayout(topSubContainerLayout);
        topSubContainerLayout.setHorizontalGroup(
            topSubContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topSubContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManualMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Run)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Stop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE)
                .addComponent(StepLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Stepcounter)
                .addGap(47, 47, 47)
                .addComponent(GemLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gemcounter)
                .addGap(93, 93, 93))
        );
        topSubContainerLayout.setVerticalGroup(
            topSubContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topSubContainerLayout.createSequentialGroup()
                .addGroup(topSubContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonMode)
                    .addComponent(ManualMode)
                    .addComponent(Run)
                    .addComponent(Stop)
                    .addComponent(GemLabel)
                    .addComponent(gemcounter)
                    .addComponent(StepLabel)
                    .addComponent(Stepcounter))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        mainContainer.add(topSubContainer, java.awt.BorderLayout.PAGE_START);

        bottomSubContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        bottomSubContainer.setMaximumSize(new java.awt.Dimension(32767, 30));
        bottomSubContainer.setMinimumSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout bottomSubContainerLayout = new javax.swing.GroupLayout(bottomSubContainer);
        bottomSubContainer.setLayout(bottomSubContainerLayout);
        bottomSubContainerLayout.setHorizontalGroup(
            bottomSubContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        bottomSubContainerLayout.setVerticalGroup(
            bottomSubContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        mainContainer.add(bottomSubContainer, java.awt.BorderLayout.PAGE_END);

        middleContainer.setBackground(new java.awt.Color(153, 153, 153));
        middleContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        middleContainer.setMaximumSize(new java.awt.Dimension(2147483647, 438));
        middleContainer.setPreferredSize(new java.awt.Dimension(975, 436));
        middleContainer.setLayout(new java.awt.BorderLayout());

        leftContainer.setMaximumSize(new java.awt.Dimension(430, 32767));
        leftContainer.setMinimumSize(new java.awt.Dimension(430, 100));
        leftContainer.setPreferredSize(new java.awt.Dimension(395, 436));
        leftContainer.setLayout(new java.awt.CardLayout());

        buttonPanel.setVisible(false);

        Go.setText("Go");
        Go.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GoActionPerformed(evt);
            }
        });

        Left.setText("Left");
        Left.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                LeftActionPerformed(evt);
            }
        });

        Right.setText("Right");
        Right.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RightActionPerformed(evt);
            }
        });

        Get.setText("Get");
        Get.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GetActionPerformed(evt);
            }
        });

        Put.setText("Put");
        Put.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(Left)
                        .addGap(71, 71, 71)
                        .addComponent(Right))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(Go))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Get)
                        .addGap(41, 41, 41)
                        .addComponent(Put)))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        buttonPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Get, Go, Left, Put, Right});

        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Go)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Left)
                    .addComponent(Right))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Get)
                    .addComponent(Put))
                .addContainerGap(321, Short.MAX_VALUE))
        );

        leftContainer.add(buttonPanel, "card2");

        manualPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Some BS here about welcome to karel or map info etc.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        manualPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Manual Programmer text box\n\nChange the name of this textbox so its not \n\n\n\n\nso\n\n\n\n\ngeneric\n\nand\n\ntesting\nthe\nscroll\nbar\ndoes\nit\nwork\nor\ndoes\nit\nsuck");
        jScrollPane1.setViewportView(jTextArea1);

        manualPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        leftContainer.add(manualPanel, "card3");

        middleContainer.add(leftContainer, java.awt.BorderLayout.LINE_START);

        rightContainer.setMinimumSize(new java.awt.Dimension(589, 100));
        rightContainer.setPreferredSize(new java.awt.Dimension(589, 469));
        rightContainer.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout worldLayout = new javax.swing.GroupLayout(world);
        world.setLayout(worldLayout);
        worldLayout.setHorizontalGroup(
            worldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );
        worldLayout.setVerticalGroup(
            worldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        rightContainer.add(world);

        middleContainer.add(rightContainer, java.awt.BorderLayout.CENTER);

        mainContainer.add(middleContainer, java.awt.BorderLayout.CENTER);

        SaveCodeChoice.setText("File");

        New.setText("New Map from File");
        New.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                NewActionPerformed(evt);
            }
        });
        SaveCodeChoice.add(New);

        Save.setText("Save");
        SaveCodeChoice.add(Save);

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CloseActionPerformed(evt);
            }
        });
        SaveCodeChoice.add(Close);

        MenuBar.add(SaveCodeChoice);

        jMenu2.setText("Help");

        jMenuItem3.setText("Open Help File (pdf)");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        MenuBar.add(jMenu2);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonModeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ButtonModeActionPerformed
    {//GEN-HEADEREND:event_ButtonModeActionPerformed
        manualPanel.setVisible(false);
        buttonPanel.setVisible(true);
    }//GEN-LAST:event_ButtonModeActionPerformed

    private void GoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GoActionPerformed
    {//GEN-HEADEREND:event_GoActionPerformed
        world.choiceMade("go");
        Stepcounter.setText("" + world.getStepCount());
        buttonPanel.setVisible(false);
    }//GEN-LAST:event_GoActionPerformed

    private void LeftActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_LeftActionPerformed
    {//GEN-HEADEREND:event_LeftActionPerformed
        world.choiceMade("left");
    }//GEN-LAST:event_LeftActionPerformed

    private void RightActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RightActionPerformed
    {//GEN-HEADEREND:event_RightActionPerformed
        world.choiceMade("right");
    }//GEN-LAST:event_RightActionPerformed

    private void GetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GetActionPerformed
    {//GEN-HEADEREND:event_GetActionPerformed
        world.choiceMade("get");
        gemcounter.setText("" + world.getPlayerGem());
    }//GEN-LAST:event_GetActionPerformed

    private void PutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PutActionPerformed
    {//GEN-HEADEREND:event_PutActionPerformed
        world.choiceMade("put");
        gemcounter.setText("" + world.getPlayerGem());
    }//GEN-LAST:event_PutActionPerformed

    private void ManualModeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ManualModeActionPerformed
    {//GEN-HEADEREND:event_ManualModeActionPerformed
        manualPanel.setVisible(true);
        buttonPanel.setVisible(false);
        world.actions();
    }//GEN-LAST:event_ManualModeActionPerformed

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
    //New file - insert a new map 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_NewActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    //Open help file (write help file...)
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void RunActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RunActionPerformed
    {//GEN-HEADEREND:event_RunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RunActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CloseActionPerformed
    {//GEN-HEADEREND:event_CloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Karel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Karel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Karel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Karel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                Karel karel = new Karel();
                karel.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonMode;
    private javax.swing.JMenuItem Close;
    private javax.swing.JLabel GemLabel;
    private javax.swing.JButton Get;
    private javax.swing.JButton Go;
    private javax.swing.JButton Left;
    private javax.swing.JButton ManualMode;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem New;
    private javax.swing.JButton Put;
    private javax.swing.JButton Right;
    private javax.swing.JButton Run;
    private javax.swing.JMenuItem Save;
    private javax.swing.JMenu SaveCodeChoice;
    private javax.swing.JLabel StepLabel;
    private javax.swing.JLabel Stepcounter;
    private javax.swing.JButton Stop;
    private javax.swing.JPanel bottomSubContainer;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel gemcounter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel leftContainer;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel manualPanel;
    private javax.swing.JPanel middleContainer;
    private javax.swing.JPanel rightContainer;
    private javax.swing.JPanel topSubContainer;
    private karel.World world;
    // End of variables declaration//GEN-END:variables
}
